# Example usage:
# import:
#   - /PATH_TO_USER_HOME/.config/alacritty/base.yml

env:
  TERM: alacritty
  LANG: ru_RU.UTF-8
  LC_CTYPE: ru_RU.UTF-8

window:
  # Fix macOS Misson Control's animations perf
  # https://github.com/alacritty/alacritty/issues/4474
  # opacity: 0.999
  decorations: buttonless

font:
  normal:
    family: Iosevka Nerd Font
    style: Regular

  bold:
    family: Iosevka Nerd Font
    style: Medium

  italic:
    family: Iosevka Nerd Font
    style: Italic

  use_thin_strokes: true

colors:
  primary:
    background: '0x181818'
    foreground: '0xd8d8d8'

shell:
  program: /usr/local/bin/fish
  args:
    - -l
    - -i
    - -c
    - '~/.start_tmux.sh'

alt_send_esc: true

mouse:
  hide_when_typing: true

# ASCII hex to Key:
# echo 0x6b | xxd -r
#
# Key to ASCII hex interactivly:
# xxd -ps -c1

key_bindings:
  # Control + ^
  - { key: Key6, mods: Control|Shift, chars: "\x1e" }

  - key: Back
    mods: Command
    chars: "\x1e"

  # Switch to next tmux pane (o)
  - { key: O, mods: Command|Shift, chars: "\x13\x6f" }

  # Switch tmux sessions (())
  - { key: LBracket, mods: Alt, chars: "\x13\x28" }
  - { key: RBracket, mods: Alt, chars: "\x13\x29" }

  # Switch tmux windows ([])
  - { key: LBracket, mods: Command|Shift, chars: "\x13\x70" }
  - { key: RBracket, mods: Command|Shift, chars: "\x13\x6e" }

  # Switch (neo)vim tabpages (gT/gt)
  - { key: LBracket, mods: Command, chars: "\x67\x54" }
  - { key: RBracket, mods: Command, chars: "\x67\x74" }

  # Switch to last pane(;) / window(l)
  - { key: P, mods: Command, chars: "\x13\x3b" }
  - { key: P, mods: Command|Shift, chars: "\x13\x6c" }

  # Move tmux windows (<>)
  - { key: Left, mods: Command|Shift, chars: "\x13\x3c" }
  - { key: Right, mods: Command|Shift, chars: "\x13\x3e" }

  # Enter tmux copy mode ([)
  - { key: F, mods: Command, chars: "\x13\x5b" }

  # No Hide action
  - { key: H, mods: Command, action: None }

  # Clear buffer and history (k)
  - { key: R, mods: Command, command: { program: "/usr/local/bin/tmux", args: ["send-keys", "-R"] } }
  - { key: K, mods: Command, action: ClearHistory }
  - { key: K, mods: Command, chars: "\x13\x4b" }

  # New tmux window (c)
  - { key: T, mods: Command, chars: "\x13\x63" }

  # New tmux session (S)
  - { key: N, mods: Command, chars: "\x13\x53" }

  # Open specific programs
  - key: Comma
    mods: Command
    chars: "\x13\x41" # prefix + A
    # command:
    #   program: "/usr/local/bin/tmux"
    #   args: ["new-window", "-nalacritty.yml", "nvim ~/dotfiles/alacritty/.config/alacritty/alacritty.yml"]

  - key: Slash
    mods: Command
    chars: "\x13\x48" # prefix + H
    # command:
    #   program: "/usr/local/bin/tmux"
    #   args: ["new-window", "-nhelp.txt", "nvim -c 'help | only'"]

  - key: Semicolon
    mods: Command
    chars: "\x13\x47" # prefix + G
    # command:
    #   program: "/usr/local/bin/tmux"
    #   args: ["new-window", "-nMonitor", "glances"]

  - key: T
    mods: Command|Shift
    chars: "\x13\x54" # prefix + T
    # command:
    #   program: "/usr/local/bin/tmux"
    #   args: ["new-window", "-ntranslate", "trans -d -I"]

  # (NEO)VIM related bindings
  - { key: J, mods: Alt, chars: "8j" }
  - { key: K, mods: Alt, chars: "8k" }
  - { key: W, mods: Command, chars: ":q\x0d" }
  - { key: S, mods: Command, chars: ":w\x0d" }

  # word navigation
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

  # Alt bindings
  - { key: A, mods: Alt, chars: "\x1ba" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: C, mods: Alt, chars: "\x1bc" }
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: E, mods: Alt, chars: "\x1be" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: G, mods: Alt, chars: "\x1bg" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: I, mods: Alt, chars: "\x1bi" }
# - { key: J, mods: Alt, chars: "\x1bj" }
# - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: L, mods: Alt, chars: "\x1bl" }
  - { key: M, mods: Alt, chars: "\x1bm" }
  - { key: N, mods: Alt, chars: "\x1bn" }
  - { key: O, mods: Alt, chars: "\x1bo" }
  - { key: P, mods: Alt, chars: "\x1bp" }
  - { key: Q, mods: Alt, chars: "\x1bq" }
  - { key: R, mods: Alt, chars: "\x1br" }
  - { key: S, mods: Alt, chars: "\x1bs" }
  - { key: T, mods: Alt, chars: "\x1bt" }
  - { key: U, mods: Alt, chars: "\x1bu" }
  - { key: V, mods: Alt, chars: "\x1bv" }
  - { key: W, mods: Alt, chars: "\x1bw" }
  - { key: X, mods: Alt, chars: "\x1bx" }
  - { key: Y, mods: Alt, chars: "\x1by" }
  - { key: Z, mods: Alt, chars: "\x1bz" }
  - { key: A, mods: Alt|Shift, chars: "\x1bA" }
  - { key: B, mods: Alt|Shift, chars: "\x1bB" }
  - { key: C, mods: Alt|Shift, chars: "\x1bC" }
  - { key: D, mods: Alt|Shift, chars: "\x1bD" }
  - { key: E, mods: Alt|Shift, chars: "\x1bE" }
  - { key: F, mods: Alt|Shift, chars: "\x1bF" }
  - { key: G, mods: Alt|Shift, chars: "\x1bG" }
  - { key: H, mods: Alt|Shift, chars: "\x1bH" }
  - { key: I, mods: Alt|Shift, chars: "\x1bI" }
  - { key: J, mods: Alt|Shift, chars: "\x1bJ" }
  - { key: K, mods: Alt|Shift, chars: "\x1bK" }
  - { key: L, mods: Alt|Shift, chars: "\x1bL" }
  - { key: M, mods: Alt|Shift, chars: "\x1bM" }
  - { key: N, mods: Alt|Shift, chars: "\x1bN" }
  - { key: O, mods: Alt|Shift, chars: "\x1bO" }
  - { key: P, mods: Alt|Shift, chars: "\x1bP" }
  - { key: Q, mods: Alt|Shift, chars: "\x1bQ" }
  - { key: R, mods: Alt|Shift, chars: "\x1bR" }
  - { key: S, mods: Alt|Shift, chars: "\x1bS" }
  - { key: T, mods: Alt|Shift, chars: "\x1bT" }
  - { key: U, mods: Alt|Shift, chars: "\x1bU" }
  - { key: V, mods: Alt|Shift, chars: "\x1bV" }
  - { key: W, mods: Alt|Shift, chars: "\x1bW" }
  - { key: X, mods: Alt|Shift, chars: "\x1bX" }
  - { key: Y, mods: Alt|Shift, chars: "\x1bY" }
  - { key: Z, mods: Alt|Shift, chars: "\x1bZ" }
